import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import Header from '@/components/header'
import { Toaster } from 'sonner'
import { cookies } from 'next/headers'
import SlideSession from '@/components/slide-session'
import { AppProvider } from '@/app/app-provider'

const inter = Inter({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const sessionToken = cookieStore.get('sessionToken')?.value || ''

  return (
    <>
      <html lang='en' suppressHydrationWarning>
        <head />
        <body className={`${inter.className}`}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
            <Header />
            <AppProvider initialSessionToken={sessionToken}>
              {children}
              <SlideSession />
            </AppProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
